In [17]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [26]:
df = pd.read_csv('pca.csv',header=1)

In [27]:
df.iloc[:,0:3]

1.3440932289918300  -0.6500239344068980  -0.9327314972765400
0             0.487577             0.534506            -1.533331
1             2.614491            -0.600424            -0.192749
2             0.305702             0.457773            -1.714151
3            -0.318285            -1.912255             2.074144
4             1.494670             1.205995             0.533016
..                 ...                  ...                  ...
94            1.584237            -1.258505             0.876358
95            0.132375            -1.443855            -1.528990
96            2.265153             0.670481            -0.378776
97           -0.949061            -1.517874            -1.741572
98            2.540817             0.418398             0.208488

[99 rows x 3 columns]

In [28]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:3],df.iloc[:,3],
                                                 test_size=0.1)

In [29]:
lr = LogisticRegression()

In [30]:
model = lr.fit(x_train,y_train)

In [31]:
y_pred = model.predict(x_test)

In [32]:
accuracy = accuracy_score(y_test,y_pred)

In [33]:
accuracy

0.9

In [36]:
cov_matrix = np.cov(x_train,rowvar=False)

In [48]:
cov_matrix

array([[ 1.47751149, -0.03138288,  0.12729213],
       [-0.03138288,  1.16869195,  0.16071366],
       [ 0.12729213,  0.16071366,  1.51639973]])

In [49]:
eigenvalues,eigenvectors = np.linalg.eig(cov_matrix)

In [50]:
eigenvalues

array([1.65007843, 1.42244632, 1.09007842])

In [51]:
eigenvectors

array([[ 0.54972434, -0.810253  ,  0.20320733],
       [ 0.23206897,  0.38181768,  0.894628  ],
       [ 0.80246317,  0.44464067, -0.39792905]])

In [76]:
e1 = pd.DataFrame(eigenvectors)

In [77]:
pc1_train = np.dot(x_train,e1)

In [78]:
model.fit(pd.DataFrame(pc1_train),y_train)

LogisticRegression()

In [79]:
pc1_test = np.dot(x_test,e1)

In [80]:
y_pred_pca = model.predict(pd.DataFrame(pc1_test))

In [81]:
accuracy_pca = accuracy_score(y_test,y_pred_pca)

In [82]:
accuracy_pca

0.9